### ISSUE TITLE
Multi-folder scope

### ISSUE THREAD

**Issue by danieliser** [rhalaly/scope-to-this-vscode#1]
First, what an awesome extension. Feels like a hit.

That said would be great if you could select 2 or more folders for the scope.

Currently if I select 2 folders in the same parent directory it will set the scope to the parent and show all children.

I can then of course hide the other folders in that area but that isn't ideal.

**Comment by rhalaly** [comment]
This extension supports only one folder to scope to.

> Currently if I select 2 folders in the same parent directory it will set the scope to the parent and show all children.

This behavior is a bug. When you select the second scope the first one should be cleared. If you can add a repro to this it would be nice 😄.

As I mentioned in the other issue you open, this extension adds glob patterns that **hide everything except** the folder you select, because this is VSCode works. This is a tricky operation with tricky patterns, and there is no straightforward way to manage two or more scopes with such a filter.
