### ISSUE TITLE
add ability to choose multiple directories to scope to

### ISSUE THREAD

**Issue by umed** [rhalaly/scope-to-this-vscode#7]
I want to select multiple directories on the same level and then scope to them

**Comment by rhalaly** [comment]
This feature is not supported by VSCode currently. To scope to directory, we set some complex rules that hide everything but the selected folder. If you want to scope several directories on the same level, you can select the direct parent directory as a scope. That will leave only it and its children visible.

**Comment by hoppalotta** [comment]
Thanks for the extension. This multiple selection would be really valuable to us if supported some day!

**Comment by rhalaly** [comment]
@hoppalotta since this extension uses the built-in Explorer panel, we are limited to its capabilities. This is also the reason that we have "known issues". 

To support multi scopes independently we can create additional "Folders" tree view, and customize as we want. It may work but it requires a lot of effort to implement, and I don't have the bandwidth to do this. (I didn't find a way to reuse the vscode built-in file explorer tree view in an extension code)

And, of course, PRs are welcome 😄!
